let authMode='login';
function setAuthMode(mode){authMode=mode;document.getElementById('loginTab').classList.toggle('active',mode==='login');document.getElementById('signupTab').classList.toggle('active',mode==='signup');document.getElementById('authNameField').classList.toggle('hidden',mode!=='signup');document.getElementById('authSubmit').textContent=mode==='login'?'登入':'建立帳號';showAuthMessage('',false)}
function showAuthMessage(text,ok=false){const el=document.getElementById('authMessage');el.textContent=text||'';el.className='auth-message'+(text?' show '+(ok?'ok':'err'):'')}
function friendlyAuthError(error){const m=String(error?.message||error||'發生未知錯誤');if(/Invalid login credentials/i.test(m))return 'Email 或密碼不正確。';if(/User already registered/i.test(m))return '這個 Email 已經註冊，請直接登入。';if(/Password should be/i.test(m))return '密碼長度不足，請至少輸入 6 個字元。';if(/rate limit/i.test(m))return '操作太頻繁，請稍後再試。';return m}
async function submitAuth(){const email=document.getElementById('authEmail').value.trim();const password=document.getElementById('authPassword').value;const btn=document.getElementById('authSubmit');if(!email||!password){showAuthMessage('請輸入 Email 與密碼。');return}btn.disabled=true;btn.textContent='處理中…';try{if(authMode==='signup'){const display_name=document.getElementById('authDisplayName').value.trim();const {data,error}=await cloud.auth.signUp({email,password,options:{data:{display_name},emailRedirectTo:'https://katy0409.github.io/quit-gambling/'}});if(error)throw error;if(data.session){showAuthMessage('帳號建立成功，已登入。',true);await applySession(data.session)}else{showAuthMessage('帳號已建立，請到信箱完成驗證後再登入。',true);setAuthMode('login')}}else{const {data,error}=await cloud.auth.signInWithPassword({email,password});if(error)throw error;showAuthMessage('登入成功。',true);await applySession(data.session)}}catch(e){console.error(e);showAuthMessage(friendlyAuthError(e))}finally{btn.disabled=false;btn.textContent=authMode==='login'?'登入':'建立帳號'}}
async function sendResetPassword(){const email=document.getElementById('authEmail').value.trim();if(!email){showAuthMessage('請先輸入要重設密碼的 Email。');return}try{const {error}=await cloud.auth.resetPasswordForEmail(email,{redirectTo:'https://katy0409.github.io/quit-gambling/reset-password'});if(error)throw error;showAuthMessage('重設密碼信已寄出，請檢查信箱。',true)}catch(e){showAuthMessage(friendlyAuthError(e))}}
async function applySession(session){const gate=document.getElementById('authGate');const email=session?.user?.email||'';gate.classList.toggle('hidden',!!session);document.getElementById('accountEmail').textContent=email||'尚未登入';if(session){try{await cloud.from('profiles').upsert({id:session.user.id,email,display_name:session.user.user_metadata?.display_name||''},{onConflict:'id'})}catch(e){console.warn('profile upsert',e)}}}
async function logoutCloud(){if(!confirm('確定登出雲端帳號？本機資料仍會保留。'))return;await cloud.auth.signOut();await applySession(null)}
async function initCloudAuth(){const {data,error}=await cloud.auth.getSession();if(error)console.warn(error);await applySession(data?.session||null);cloud.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>applySession(session),0)})}
window.addEventListener('DOMContentLoaded',initCloudAuth);
