-- =========================================================
-- Restart V13.16：SQL 4 完整整合版
-- 用途：玩家意見、戒賭幣錢包、戒賭幣紀錄、管理員後台、商城扣幣、每日任務、完整重置
-- 可重複執行；不會刪除資料表本身
-- =========================================================

begin;

-- =========================================================
-- 1. 玩家意見回饋
-- =========================================================
create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null default 'other'
    check (category in ('bug', 'feature', 'avatar', 'shop', 'square', 'other')),
  message text not null check (char_length(message) between 1 and 2000),
  status text not null default 'open'
    check (status in ('open', 'processing', 'done')),
  admin_reply text,
  app_version text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'feedback' and column_name = 'admin_reply'
  ) then
    alter table public.feedback add column admin_reply text;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'feedback' and column_name = 'status'
  ) then
    alter table public.feedback
      add column status text not null default 'open'
      check (status in ('open', 'processing', 'done'));
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'feedback' and column_name = 'app_version'
  ) then
    alter table public.feedback add column app_version text;
  end if;

  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'feedback' and column_name = 'updated_at'
  ) then
    alter table public.feedback add column updated_at timestamptz not null default now();
  end if;
end
$$;

alter table public.feedback enable row level security;

drop policy if exists "users can submit feedback" on public.feedback;
create policy "users can submit feedback"
on public.feedback
for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "users can view own feedback" on public.feedback;
create policy "users can view own feedback"
on public.feedback
for select
to authenticated
using ((select auth.uid()) = user_id);

-- =========================================================
-- 2. 玩家戒賭幣錢包
-- =========================================================
create table if not exists public.player_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  tokens integer not null default 10 check (tokens >= 0),
  updated_at timestamptz not null default now()
);

-- =========================================================
-- 3. 戒賭幣異動紀錄
-- =========================================================
create table if not exists public.coin_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  balance_after integer not null check (balance_after >= 0),
  reason text not null default '戒賭幣異動',
  operator_type text not null default 'system',
  created_at timestamptz not null default now()
);

create index if not exists idx_coin_transactions_user_created
on public.coin_transactions(user_id, created_at desc);

alter table public.player_wallets enable row level security;
alter table public.coin_transactions enable row level security;

drop policy if exists "wallet owner read" on public.player_wallets;
create policy "wallet owner read"
on public.player_wallets
for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "coin owner read" on public.coin_transactions;
create policy "coin owner read"
on public.coin_transactions
for select
to authenticated
using ((select auth.uid()) = user_id);

-- =========================================================
-- 4. 一般玩家建立／取得錢包
-- =========================================================
create or replace function public.ensure_wallet_v134()
returns public.player_wallets
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  w public.player_wallets;
begin
  if uid is null then
    raise exception '請先登入';
  end if;

  insert into public.player_wallets (user_id, tokens)
  values (uid, 10)
  on conflict (user_id) do nothing;

  select * into w
  from public.player_wallets
  where user_id = uid;

  if not exists (
    select 1 from public.coin_transactions where user_id = uid
  ) then
    insert into public.coin_transactions (
      user_id, amount, balance_after, reason, operator_type
    ) values (
      uid, 10, w.tokens, '一般玩家新手禮物', 'system'
    );
  end if;

  return w;
end;
$$;

-- =========================================================
-- 5. 管理員：查看玩家
-- =========================================================
create or replace function public.admin_list_players_v134(admin_password text)
returns table (
  user_id uuid,
  email text,
  display_name text,
  tokens integer
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if admin_password <> '03070718' then
    raise exception '管理員密碼錯誤';
  end if;

  return query
  select
    u.id,
    u.email::text,
    coalesce(p.display_name, ''),
    coalesce(w.tokens, 10)
  from auth.users u
  left join public.profiles p on p.id = u.id
  left join public.player_wallets w on w.user_id = u.id
  order by u.created_at desc;
end;
$$;

-- =========================================================
-- 6. 管理員：新增／扣除玩家戒賭幣
-- =========================================================
create or replace function public.admin_adjust_coins_v134(
  admin_password text,
  target_user uuid,
  coin_delta integer,
  change_reason text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  old_balance integer;
  new_balance integer;
  actual_delta integer;
begin
  if admin_password <> '03070718' then
    raise exception '管理員密碼錯誤';
  end if;

  if target_user is null then
    raise exception '找不到玩家';
  end if;

  if coin_delta is null or coin_delta = 0 then
    raise exception '異動數量不可為 0';
  end if;

  insert into public.player_wallets (user_id, tokens)
  values (target_user, 10)
  on conflict (user_id) do nothing;

  select tokens into old_balance
  from public.player_wallets
  where user_id = target_user
  for update;

  new_balance := greatest(0, old_balance + coin_delta);
  actual_delta := new_balance - old_balance;

  update public.player_wallets
  set tokens = new_balance,
      updated_at = now()
  where user_id = target_user;

  insert into public.coin_transactions (
    user_id, amount, balance_after, reason, operator_type
  ) values (
    target_user,
    actual_delta,
    new_balance,
    coalesce(nullif(trim(change_reason), ''), '管理員調整'),
    'admin'
  );

  return new_balance;
end;
$$;

-- =========================================================
-- 7. 管理員：查看玩家意見
-- =========================================================
create or replace function public.admin_list_feedback_v134(admin_password text)
returns table (
  id text,
  user_id uuid,
  email text,
  display_name text,
  category text,
  message text,
  status text,
  admin_reply text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
begin
  if admin_password <> '03070718' then
    raise exception '管理員密碼錯誤';
  end if;

  return query
  select
    f.id::text,
    f.user_id,
    u.email::text,
    coalesce(p.display_name, ''),
    f.category,
    f.message,
    coalesce(f.status, 'open'),
    f.admin_reply,
    f.created_at
  from public.feedback f
  left join auth.users u on u.id = f.user_id
  left join public.profiles p on p.id = f.user_id
  order by f.created_at desc;
end;
$$;

-- =========================================================
-- 8. 管理員：回覆玩家意見
-- =========================================================
create or replace function public.admin_reply_feedback_v134(
  admin_password text,
  feedback_id text,
  reply_text text,
  new_status text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  safe_status text;
begin
  if admin_password <> '03070718' then
    raise exception '管理員密碼錯誤';
  end if;

  safe_status := coalesce(nullif(new_status, ''), 'processing');

  if safe_status not in ('open', 'processing', 'done') then
    raise exception '無效的處理狀態';
  end if;

  update public.feedback
  set admin_reply = reply_text,
      status = safe_status,
      updated_at = now()
  where id::text = feedback_id;

  return found;
end;
$$;

-- =========================================================
-- 9. 每日任務領取紀錄
-- =========================================================
create table if not exists public.daily_task_claims (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  task_date date not null default current_date,
  task_key text not null,
  reward integer not null check (reward > 0),
  created_at timestamptz not null default now(),
  unique (user_id, task_date, task_key)
);

create index if not exists idx_daily_task_claims_user_date
on public.daily_task_claims(user_id, task_date desc);

alter table public.daily_task_claims enable row level security;

drop policy if exists "users view own daily claims" on public.daily_task_claims;
create policy "users view own daily claims"
on public.daily_task_claims
for select
to authenticated
using ((select auth.uid()) = user_id);

-- =========================================================
-- 10. 商城真正扣除戒賭幣
-- =========================================================
create or replace function public.spend_coins_v135(
  spend_amount integer,
  spend_reason text default '商城購買'
)
returns table (tokens integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  current_tokens integer;
begin
  if uid is null then
    raise exception '尚未登入';
  end if;

  if spend_amount is null or spend_amount <= 0 then
    raise exception '扣款金額錯誤';
  end if;

  perform public.ensure_wallet_v134();

  select w.tokens into current_tokens
  from public.player_wallets w
  where w.user_id = uid
  for update;

  if current_tokens < spend_amount then
    raise exception '戒賭幣不足';
  end if;

  current_tokens := current_tokens - spend_amount;

  update public.player_wallets
  set tokens = current_tokens,
      updated_at = now()
  where user_id = uid;

  insert into public.coin_transactions (
    user_id, amount, balance_after, reason, operator_type
  ) values (
    uid,
    -spend_amount,
    current_tokens,
    coalesce(nullif(trim(spend_reason), ''), '商城購買'),
    'player'
  );

  return query select current_tokens;
end;
$$;

-- =========================================================
-- 11. 領取每日任務獎勵
-- =========================================================
create or replace function public.claim_daily_task_v135(
  task_key text,
  reward_amount integer
)
returns table (tokens integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  current_tokens integer;
begin
  if uid is null then
    raise exception '尚未登入';
  end if;

  if task_key is null or trim(task_key) = '' then
    raise exception '任務代碼錯誤';
  end if;

  if task_key not in ('login', 'checkin', 'journal', 'square', 'avatar') then
    raise exception '無效的每日任務';
  end if;

  if reward_amount not between 1 and 10 then
    raise exception '獎勵金額錯誤';
  end if;

  perform public.ensure_wallet_v134();

  insert into public.daily_task_claims (
    user_id, task_date, task_key, reward
  ) values (
    uid, current_date, task_key, reward_amount
  );

  update public.player_wallets
  set tokens = player_wallets.tokens + reward_amount,
      updated_at = now()
  where user_id = uid
  returning player_wallets.tokens into current_tokens;

  insert into public.coin_transactions (
    user_id, amount, balance_after, reason, operator_type
  ) values (
    uid,
    reward_amount,
    current_tokens,
    '每日任務：' || task_key,
    'system'
  );

  return query select current_tokens;

exception
  when unique_violation then
    raise exception '今天已領取此任務';
end;
$$;

-- =========================================================
-- 12. 管理員：完整重置指定玩家
-- 前端呼叫名稱與參數：
-- admin_full_reset_user_v1314(admin_password, reset_reason, target_user)
-- =========================================================
drop function if exists public.admin_full_reset_player_v1314(text, uuid, text);
drop function if exists public.admin_full_reset_user_v1314(text, text, uuid);
create or replace function public.admin_full_reset_user_v1314(
  admin_password text,
  reset_reason text,
  target_user uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  safe_reason text;
  reset_time timestamptz := now();
begin
  if admin_password <> '03070718' then
    raise exception '管理員密碼錯誤';
  end if;

  if target_user is null then
    raise exception '找不到玩家';
  end if;

  if not exists (
    select 1 from auth.users where id = target_user
  ) then
    raise exception '玩家帳號不存在';
  end if;

  safe_reason := nullif(trim(reset_reason), '');

  if safe_reason is null then
    raise exception '請填寫完整重置原因';
  end if;

  -- 先刪除有外鍵依賴的資料
  delete from public.transactions where user_id = target_user;
  delete from public.saving_goals where user_id = target_user;
  delete from public.debts where user_id = target_user;
  delete from public.assets where user_id = target_user;

  -- 其他玩家資料
  delete from public.categories where user_id = target_user;
  delete from public.diaries where user_id = target_user;
  delete from public.checkins where user_id = target_user;
  delete from public.relapses where user_id = target_user;
  delete from public.photos where user_id = target_user;
  delete from public.finance_reports where user_id = target_user;
  delete from public.excel_import_logs where user_id = target_user;
  delete from public.daily_task_claims where user_id = target_user;
  delete from public.feedback where user_id = target_user;
  delete from public.square_messages where user_id = target_user;

  -- 清除舊戒賭幣紀錄
  delete from public.coin_transactions where user_id = target_user;

  -- 錢包恢復 10 枚
  insert into public.player_wallets (user_id, tokens, updated_at)
  values (target_user, 10, reset_time)
  on conflict (user_id)
  do update set
    tokens = excluded.tokens,
    updated_at = excluded.updated_at;

  -- 重建設定，並留下前端清除本機角色／衣櫃／商城資料所需的標記
  delete from public.settings where user_id = target_user;

  insert into public.settings (
    user_id,
    home_title,
    home_subtitle,
    theme_color,
    salary_amount,
    line_url,
    extra,
    created_at,
    updated_at
  ) values (
    target_user,
    '重新開始',
    '今天不賭，因為我值得更好的生活。',
    '#f7f3ed',
    0,
    null,
    jsonb_build_object(
      'admin_full_reset_at', reset_time,
      'admin_full_reset_reason', safe_reason,
      'admin_full_reset_version', 'v13.16',
      'admin_full_reset_requested', true
    ),
    reset_time,
    reset_time
  );

  -- 保留管理員完整重置紀錄
  insert into public.coin_transactions (
    user_id,
    amount,
    balance_after,
    reason,
    operator_type,
    created_at
  ) values (
    target_user,
    10,
    10,
    '管理員完整重置：' || safe_reason,
    'admin',
    reset_time
  );

  -- 只保留 Auth 登入帳號；清除玩家暱稱與頭像
  update public.profiles
  set display_name = null,
      avatar_url = null,
      updated_at = reset_time
  where id = target_user;

  return true;
end;
$$;


-- =========================================================
-- 13. Restart 廣場聊天
-- =========================================================
create table if not exists public.square_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null default '玩家',
  message text not null check (char_length(trim(message)) between 1 and 200),
  created_at timestamptz not null default now()
);
create index if not exists idx_square_messages_created on public.square_messages(created_at desc);
alter table public.square_messages enable row level security;
drop policy if exists "authenticated read square messages" on public.square_messages;
create policy "authenticated read square messages" on public.square_messages for select to authenticated using (true);
drop policy if exists "authenticated send square messages" on public.square_messages;
create policy "authenticated send square messages" on public.square_messages for insert to authenticated with check ((select auth.uid()) = user_id);
-- 不建立玩家 update/delete policy，玩家不可修改或刪除訊息。

do $$ begin
  alter publication supabase_realtime add table public.square_messages;
exception when duplicate_object then null;
end $$;

create or replace function public.admin_list_square_messages_v1315(admin_password text)
returns table(id text,user_id uuid,email text,display_name text,message text,created_at timestamptz)
language plpgsql security definer set search_path=public,auth as $$
begin
 if admin_password <> '03070718' then raise exception '管理員密碼錯誤'; end if;
 return query select m.id::text,m.user_id,u.email::text,m.display_name,m.message,m.created_at from public.square_messages m left join auth.users u on u.id=m.user_id order by m.created_at desc limit 200;
end;$$;
create or replace function public.admin_delete_square_message_v1315(admin_password text,message_id text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
 if admin_password <> '03070718' then raise exception '管理員密碼錯誤'; end if;
 delete from public.square_messages where id::text=message_id; return found;
end;$$;

-- =========================================================
-- 14. 函式執行權限
-- =========================================================
revoke all on function public.ensure_wallet_v134() from public;
revoke all on function public.spend_coins_v135(integer, text) from public;
revoke all on function public.claim_daily_task_v135(text, integer) from public;
revoke all on function public.admin_full_reset_user_v1314(text, text, uuid) from public;

grant execute on function public.ensure_wallet_v134() to authenticated;
grant execute on function public.spend_coins_v135(integer, text) to authenticated;
grant execute on function public.claim_daily_task_v135(text, integer) to authenticated;

grant execute on function public.admin_list_players_v134(text) to anon, authenticated;
grant execute on function public.admin_adjust_coins_v134(text, uuid, integer, text) to anon, authenticated;
grant execute on function public.admin_list_feedback_v134(text) to anon, authenticated;
grant execute on function public.admin_reply_feedback_v134(text, text, text, text) to anon, authenticated;
grant execute on function public.admin_full_reset_user_v1314(text, text, uuid) to anon, authenticated;
grant execute on function public.admin_list_square_messages_v1315(text) to anon, authenticated;
grant execute on function public.admin_delete_square_message_v1315(text, text) to anon, authenticated;

commit;
